### ISSUE TITLE
Coroot agent overlap with postgres_exporter

### ISSUE THREAD

**Issue by montag** [coroot/coroot-aws-agent#1]
Do you consider the coroot agent to be a replacement for the prometheus_postgres_exporter or do they complement each other? 

It's hard to tell how much overlap there is between the two packages. 

Thanks!

**Comment by def** [comment]
Yes, we see pg-agent as a replacement for postgres_exporter. At least I don't see what metrics gathered by postgres_exporter would be useful in troubleshooting Postgres-related issues.

**Comment by montag** [comment]
Thanks for input!
