### ISSUE TITLE
High memory and cpu usage and OOM loop

### ISSUE THREAD

**Issue by YoranSys** [coroot/coroot-aws-agent#3]
Hi,

we are experiencing high memory usage and OOM kill loop while using AWS agent in our EKS cluster. Also we have an heavy cpu usage above 5 cpu.

 AWS agent container tries to allocate more than 5GiB of memory before it is killed. 

We have 70 rds connected after 20 min of uptime it's impossible to scrape we have many logs with db metrics collected above 5 min like this one `db metrics collected in: 4m39.907921662s`

![image](https://user-images.githubusercontent.com/11197007/224284460-3f7d1e6d-26c0-4c86-b63f-67002a667199.png)
![image](https://user-images.githubusercontent.com/11197007/224284485-9bf356d0-4a2a-4ca3-9e31-ec2891fe6136.png)

I made some dump CPU and memory profiles.
[profile-aws-agent.pb.gz](https://github.com/coroot/coroot-aws-agent/files/10940752/profile-aws-agent.pb.gz)
[heap-aws-agent.pb.gz](https://github.com/coroot/coroot-aws-agent/files/10940750/heap-aws-agent.pb.gz)

**Comment by def** [comment]
The profile appears identical to coroot/coroot-pg-agent#11.
Please upgrade the agent to version 1.1.1 and verify if the issue has been resolved.

**Comment by def** [comment]
@YoranSys v1.1.2 contains improvements aimed at reducing both memory allocations and CPU consumption. Can you test this in your environment?
